In [2]:
import numpy as np 
a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
b=np.array([6,7,8])
type(b)

numpy.ndarray

In [6]:
b.dtype

dtype('int32')

In [8]:
s=np.array([(1,2,3),(6,7,8)])
s.shape

(2, 3)

In [9]:
#printing zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
#linspace
from numpy import pi
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
#basic operations
x=np.array([20,30,40,50])
y=np.arange(4)
print(y)
print(x-y)
print(x<30)

[0 1 2 3]
[20 29 38 47]
[ True False False False]


In [24]:
A=np.array([[1,2,3],[4,5,6]])
A.ndim
B=np.array([[1,2,3],[4,6,7]])
A*B

array([[ 1,  4,  9],
       [16, 30, 42]])

In [37]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=1))# means sum of each row
print(b.min(axis=0))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[0 1 2 3]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [40]:
r=np.random.rand(4)
print(r*10)

[4.95639571 0.98938857 0.97353277 7.0550503 ]


In [51]:
#nuw pdf examples
ar=np.array([1,2,3],dtype=float)
print(ar)
ar.shape


[1. 2. 3.]


(3,)

In [8]:
import pandas as pd
import numpy as np
ar=np.array(["shyam","basha","ganesh"])
df=pd.Series(ar)
print(df)

0     shyam
1     basha
2    ganesh
dtype: object
